// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251110030852_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("PcbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Multiplier")
                        .HasColumnType("REAL");

                    b.Property<string>("ProcessTimesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PcbModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ModelCode = "RF-P50DGC /GU /GT /PR /LJ-S",
                            Multiplier = 6.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.140, \"JVK 03\": 0.140, \"RH\": 0.130, \"SMT 01\": 0.352, \"SMT 02\": 0.155, \"SMT 03\": 0.155 }",
                            ProductGroup = "Audio"
                        },
                        new
                        {
                            Id = 2,
                            ModelCode = "RF-P50DEG",
                            Multiplier = 4.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.140, \"JVK 03\": 0.140, \"RH\": 0.130, \"SMT 01\": 0.397, \"SMT 02\": 0.165, \"SMT 03\": 0.165 }",
                            ProductGroup = "Audio"
                        },
                        new
                        {
                            Id = 3,
                            ModelCode = "RF-P50DPP-S",
                            Multiplier = 4.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.140, \"JVK 03\": 0.140, \"RH\": 0.130, \"SMT 01\": 0.373, \"SMT 02\": 0.155, \"SMT 03\": 0.155 }",
                            ProductGroup = "Audio"
                        },
                        new
                        {
                            Id = 4,
                            ModelCode = "RF-P55-S",
                            Multiplier = 4.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.140, \"JVK 03\": 0.140, \"RH\": 0.109, \"SMT 01\": 0.315, \"SMT 02\": 0.155, \"SMT 03\": 0.155 }",
                            ProductGroup = "Audio"
                        },
                        new
                        {
                            Id = 5,
                            ModelCode = "RF-P155-S",
                            Multiplier = 4.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.140, \"JVK 03\": 0.140, \"RH\": 0.109, \"SMT 01\": 0.378, \"SMT 02\": 0.165, \"SMT 03\": 0.165 }",
                            ProductGroup = "Audio"
                        },
                        new
                        {
                            Id = 6,
                            ModelCode = "RF-P150DBAGA /GC",
                            Multiplier = 4.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.140, \"JVK 03\": 0.140, \"RH\": 0.109, \"SMT 01\": 0.364, \"SMT 02\": 0.165, \"SMT 03\": 0.165 }",
                            ProductGroup = "Audio"
                        },
                        new
                        {
                            Id = 7,
                            ModelCode = "RF-P150DEG",
                            Multiplier = 4.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.140, \"JVK 03\": 0.140, \"RH\": 0.109, \"SMT 01\": 0.373, \"SMT 02\": 0.155, \"SMT 03\": 0.155 }",
                            ProductGroup = "Audio"
                        },
                        new
                        {
                            Id = 8,
                            ModelCode = "RF-P150DGS",
                            Multiplier = 4.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.140, \"JVK 03\": 0.140, \"RH\": 0.109, \"SMT 01\": 0.373, \"SMT 02\": 0.155, \"SMT 03\": 0.155 }",
                            ProductGroup = "Audio"
                        },
                        new
                        {
                            Id = 9,
                            ModelCode = "RF-P150DPP-S",
                            Multiplier = 4.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.140, \"JVK 03\": 0.140, \"RH\": 0.109, \"SMT 01\": 0.373, \"SMT 02\": 0.155, \"SMT 03\": 0.155 }",
                            ProductGroup = "Audio"
                        },
                        new
                        {
                            Id = 10,
                            ModelCode = "RF-NA35R-S <A>",
                            Multiplier = 3.0,
                            ProcessTimesJson = "{ \"SMT 02\": 0.320, \"SMT 03\": 0.320 }",
                            ProductGroup = "Audio"
                        },
                        new
                        {
                            Id = 11,
                            ModelCode = "RF-NA35R-S <B>",
                            Multiplier = 3.0,
                            ProcessTimesJson = "{ \"SMT 02\": 0.140, \"SMT 03\": 0.140 }",
                            ProductGroup = "Audio"
                        },
                        new
                        {
                            Id = 12,
                            ModelCode = "RF-D10 <A> [MAIN]",
                            Multiplier = 8.0,
                            ProcessTimesJson = "{ \"SMT 02\": 0.171, \"SMT 03\": 0.171 }",
                            ProductGroup = "Audio"
                        },
                        new
                        {
                            Id = 13,
                            ModelCode = "RF-D10 <B> [MAIN]",
                            Multiplier = 8.0,
                            ProcessTimesJson = "{ \"SMT 02\": 0.352, \"SMT 03\": 0.352 }",
                            ProductGroup = "Audio"
                        },
                        new
                        {
                            Id = 14,
                            ModelCode = "RF-562DD2GCK1",
                            Multiplier = 2.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.256, \"JVK 03\": 0.256, \"RH\": 0.191, \"SMT 01\": 0.480, \"SMT 02\": 0.450, \"SMT 03\": 0.450 }",
                            ProductGroup = "Audio"
                        },
                        new
                        {
                            Id = 15,
                            ModelCode = "RF-D10 [KEY/SUB-MAIN]",
                            Multiplier = 1.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.264, \"JVK 03\": 0.264, \"RH\": 0.314, \"SMT 01\": 0.420, \"SMT 02\": 0.363, \"SMT 03\": 0.363 }",
                            ProductGroup = "Audio"
                        },
                        new
                        {
                            Id = 16,
                            ModelCode = "RF-U156-S",
                            Multiplier = 2.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.100, \"JVK 03\": 0.100, \"RH\": 0.139, \"SMT 01\": 0.432, \"SMT 02\": 0.302, \"SMT 03\": 0.302 }",
                            ProductGroup = "Audio"
                        },
                        new
                        {
                            Id = 17,
                            ModelCode = "RF-5270LJK",
                            Multiplier = 2.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.033, \"JVK 03\": 0.033, \"RH\": 0.149, \"SMT 01\": 0.315, \"SMT 02\": 0.267, \"SMT 03\": 0.267 }",
                            ProductGroup = "Audio"
                        },
                        new
                        {
                            Id = 18,
                            ModelCode = "RF-2400DEG /EB /EE",
                            Multiplier = 6.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.140, \"JVK 03\": 0.140, \"RH\": 0.108, \"SMT 01\": 0.340, \"SMT 02\": 0.163, \"SMT 03\": 0.163 }",
                            ProductGroup = "Audio"
                        },
                        new
                        {
                            Id = 19,
                            ModelCode = "RF-2400DGN /LJ",
                            Multiplier = 6.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.140, \"JVK 03\": 0.140, \"RH\": 0.158, \"SMT 01\": 0.244, \"SMT 02\": 0.163, \"SMT 03\": 0.163 }",
                            ProductGroup = "Audio"
                        },
                        new
                        {
                            Id = 20,
                            ModelCode = "RF-2400DPC /DP",
                            Multiplier = 6.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.140, \"JVK 03\": 0.140, \"RH\": 0.158, \"SMT 01\": 0.276, \"SMT 02\": 0.143, \"SMT 03\": 0.143 }",
                            ProductGroup = "Audio"
                        },
                        new
                        {
                            Id = 21,
                            ModelCode = "RF-2400DGT",
                            Multiplier = 6.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.140, \"JVK 03\": 0.140, \"RH\": 0.108, \"SMT 01\": 0.344, \"SMT 02\": 0.163, \"SMT 03\": 0.163 }",
                            ProductGroup = "Audio"
                        },
                        new
                        {
                            Id = 22,
                            ModelCode = "RF-2450-S",
                            Multiplier = 6.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.140, \"JVK 03\": 0.140, \"RH\": 0.109, \"SMT 01\": 0.264, \"SMT 02\": 0.143, \"SMT 03\": 0.143 }",
                            ProductGroup = "Audio"
                        },
                        new
                        {
                            Id = 23,
                            ModelCode = "R-2255-S",
                            Multiplier = 6.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.140, \"JVK 03\": 0.140, \"RH\": 0.109, \"SMT 01\": 0.223, \"SMT 02\": 0.143, \"SMT 03\": 0.143 }",
                            ProductGroup = "Audio"
                        },
                        new
                        {
                            Id = 24,
                            ModelCode = "REF_PASTA [1st_CM+RH 100V]",
                            Multiplier = 2.0,
                            ProcessTimesJson = "{ \"SMT 02\": 0.260, \"SMT 03\": 0.260 }",
                            ProductGroup = "Refrigerator"
                        },
                        new
                        {
                            Id = 25,
                            ModelCode = "REF_PASTA [2nd_CM+RH 100V]",
                            Multiplier = 2.0,
                            ProcessTimesJson = "{ \"SMT 02\": 0.260, \"SMT 03\": 0.260 }",
                            ProductGroup = "Refrigerator"
                        },
                        new
                        {
                            Id = 26,
                            ModelCode = "REF_PASTA [1st_CM+RH 200V]",
                            Multiplier = 2.0,
                            ProcessTimesJson = "{ \"SMT 02\": 0.260, \"SMT 03\": 0.260 }",
                            ProductGroup = "Refrigerator"
                        },
                        new
                        {
                            Id = 27,
                            ModelCode = "REF_PASTA [2nd_CM+RH 200V]",
                            Multiplier = 2.0,
                            ProcessTimesJson = "{ \"RH\": 0.376 }",
                            ProductGroup = "Refrigerator"
                        },
                        new
                        {
                            Id = 28,
                            ModelCode = "ARBPC2C00670",
                            Multiplier = 6.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.097, \"JVK 03\": 0.097, \"AVK\": 0.048, \"RH\": 0.092, \"SMT 01\": 0.477, \"SMT 02\": 0.147, \"SMT 03\": 0.147 }",
                            ProductGroup = "Refrigerator"
                        },
                        new
                        {
                            Id = 29,
                            ModelCode = "BB220",
                            Multiplier = 4.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.240, \"JVK 03\": 0.240, \"RH\": 0.800, \"SMT 02\": 0.469, \"SMT 03\": 0.469 }",
                            ProductGroup = "Refrigerator"
                        },
                        new
                        {
                            Id = 30,
                            ModelCode = "BB240",
                            Multiplier = 4.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.240, \"JVK 03\": 0.240, \"RH\": 0.800, \"SMT 02\": 0.579, \"SMT 03\": 0.579 }",
                            ProductGroup = "Refrigerator"
                        },
                        new
                        {
                            Id = 31,
                            ModelCode = "FREEZER [BG-188654]",
                            Multiplier = 6.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.097, \"JVK 03\": 0.097, \"AVK\": 0.048, \"RH\": 0.092, \"SMT 01\": 0.477, \"SMT 02\": 0.147, \"SMT 03\": 0.147 }",
                            ProductGroup = "Refrigerator"
                        },
                        new
                        {
                            Id = 32,
                            ModelCode = "LED FREEZER [BG-188642]",
                            Multiplier = 18.0,
                            ProcessTimesJson = "{ \"RH\": 0.191, \"SMT 01\": 0.065 }",
                            ProductGroup = "Refrigerator"
                        },
                        new
                        {
                            Id = 33,
                            ModelCode = "LED ARBPLLA00750 <RH>",
                            Multiplier = 1.0,
                            ProcessTimesJson = "{ \"AVK\": 0.048, \"RH\": 0.191 }",
                            ProductGroup = "Refrigerator"
                        },
                        new
                        {
                            Id = 34,
                            ModelCode = "REF-LED-2 (BG-181293)",
                            Multiplier = 1.0,
                            ProcessTimesJson = "{ \"AVK\": 0.048, \"RH\": 0.020 }",
                            ProductGroup = "Refrigerator"
                        },
                        new
                        {
                            Id = 35,
                            ModelCode = "REF-LED-3 (BG-319100)",
                            Multiplier = 1.0,
                            ProcessTimesJson = "{ \"AVK\": 0.048, \"RH\": 0.020 }",
                            ProductGroup = "Refrigerator"
                        },
                        new
                        {
                            Id = 36,
                            ModelCode = "LED-BB [ARBPLLA00302]",
                            Multiplier = 1.0,
                            ProcessTimesJson = "{ \"SMT 02\": 0.069, \"SMT 03\": 0.069 }",
                            ProductGroup = "Refrigerator"
                        },
                        new
                        {
                            Id = 37,
                            ModelCode = "VR-BB [ARBP01A00260]",
                            Multiplier = 1.0,
                            ProcessTimesJson = "{ \"AVK\": 0.018 }",
                            ProductGroup = "Refrigerator"
                        },
                        new
                        {
                            Id = 38,
                            ModelCode = "ARBGBA301650",
                            Multiplier = 6.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.097, \"JVK 03\": 0.097, \"AVK\": 0.048, \"RH\": 0.092, \"SMT 01\": 0.477, \"SMT 02\": 0.147, \"SMT 03\": 0.147 }",
                            ProductGroup = "Refrigerator"
                        },
                        new
                        {
                            Id = 39,
                            ModelCode = "BG-213400",
                            Multiplier = 14.0,
                            ProcessTimesJson = "{ \"AVK\": 0.048, \"RH\": 0.020 }",
                            ProductGroup = "Refrigerator"
                        },
                        new
                        {
                            Id = 40,
                            ModelCode = "ACXA73-37130",
                            Multiplier = 2.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.264, \"JVK 03\": 0.404, \"AVK\": 0.083, \"RH\": 0.175, \"SMT 01\": 0.631, \"SMT 02\": 0.350, \"SMT 03\": 0.350 }",
                            ProductGroup = "AC"
                        },
                        new
                        {
                            Id = 41,
                            ModelCode = "ACXA73-50470",
                            Multiplier = 2.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.264, \"JVK 03\": 0.404, \"AVK\": 0.083, \"RH\": 0.175, \"SMT 01\": 0.631, \"SMT 02\": 0.350, \"SMT 03\": 0.350 }",
                            ProductGroup = "AC"
                        },
                        new
                        {
                            Id = 42,
                            ModelCode = "ACXA73-50480",
                            Multiplier = 2.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.264, \"JVK 03\": 0.404, \"AVK\": 0.083, \"RH\": 0.175, \"SMT 01\": 0.631, \"SMT 02\": 0.350, \"SMT 03\": 0.350 }",
                            ProductGroup = "AC"
                        },
                        new
                        {
                            Id = 43,
                            ModelCode = "ACXA73-52800",
                            Multiplier = 2.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.264, \"JVK 03\": 0.404, \"AVK\": 0.083, \"RH\": 0.175, \"SMT 01\": 0.631, \"SMT 02\": 0.350, \"SMT 03\": 0.350 }",
                            ProductGroup = "AC"
                        },
                        new
                        {
                            Id = 44,
                            ModelCode = "ACXA73-52810",
                            Multiplier = 2.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.264, \"JVK 03\": 0.404, \"AVK\": 0.083, \"RH\": 0.175, \"SMT 01\": 0.631, \"SMT 02\": 0.350, \"SMT 03\": 0.350 }",
                            ProductGroup = "AC"
                        },
                        new
                        {
                            Id = 45,
                            ModelCode = "ACXA73-48700",
                            Multiplier = 2.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.264, \"JVK 03\": 0.404, \"AVK\": 0.083, \"RH\": 0.175, \"SMT 01\": 0.631, \"SMT 02\": 0.350, \"SMT 03\": 0.350 }",
                            ProductGroup = "AC"
                        },
                        new
                        {
                            Id = 46,
                            ModelCode = "ACXA73-53420",
                            Multiplier = 2.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.264, \"JVK 03\": 0.404, \"AVK\": 0.083, \"RH\": 0.175, \"SMT 01\": 0.631, \"SMT 02\": 0.350, \"SMT 03\": 0.350 }",
                            ProductGroup = "AC"
                        },
                        new
                        {
                            Id = 47,
                            ModelCode = "ACXA73-52820",
                            Multiplier = 2.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.264, \"JVK 03\": 0.404, \"AVK\": 0.083, \"RH\": 0.175, \"SMT 01\": 0.631, \"SMT 02\": 0.350, \"SMT 03\": 0.350 }",
                            ProductGroup = "AC"
                        },
                        new
                        {
                            Id = 48,
                            ModelCode = "ACXA73-52830",
                            Multiplier = 2.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.264, \"JVK 03\": 0.404, \"AVK\": 0.083, \"RH\": 0.175, \"SMT 01\": 0.631, \"SMT 02\": 0.350, \"SMT 03\": 0.350 }",
                            ProductGroup = "AC"
                        },
                        new
                        {
                            Id = 49,
                            ModelCode = "ACXA73-51410",
                            Multiplier = 2.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.264, \"JVK 03\": 0.404, \"AVK\": 0.083, \"RH\": 0.175, \"SMT 01\": 0.631, \"SMT 02\": 0.350, \"SMT 03\": 0.350 }",
                            ProductGroup = "AC"
                        },
                        new
                        {
                            Id = 50,
                            ModelCode = "1st_ACXA73-50110",
                            Multiplier = 2.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.264, \"JVK 03\": 0.404, \"AVK\": 0.083, \"RH\": 0.175, \"SMT 01\": 0.631, \"SMT 02\": 0.350, \"SMT 03\": 0.350 }",
                            ProductGroup = "AC"
                        },
                        new
                        {
                            Id = 51,
                            ModelCode = "2nd_ACXA73-50110",
                            Multiplier = 2.0,
                            ProcessTimesJson = "{ \"SMT 02\": 0.400, \"SMT 03\": 0.400 }",
                            ProductGroup = "AC"
                        },
                        new
                        {
                            Id = 52,
                            ModelCode = "1st_ACXA73-50120",
                            Multiplier = 2.0,
                            ProcessTimesJson = "{ \"JVK 02\": 0.264, \"JVK 03\": 0.404, \"AVK\": 0.083, \"RH\": 0.175, \"SMT 01\": 0.631, \"SMT 02\": 0.350, \"SMT 03\": 0.350 }",
                            ProductGroup = "AC"
                        },
                        new
                        {
                            Id = 53,
                            ModelCode = "2nd_ACXA73-50120",
                            Multiplier = 2.0,
                            ProcessTimesJson = "{ \"SMT 02\": 0.400, \"SMT 03\": 0.400 }",
                            ProductGroup = "AC"
                        },
                        new
                        {
                            Id = 54,
                            ModelCode = "LED-22280 [ACXE39C01000ID]",
                            Multiplier = 10.0,
                            ProcessTimesJson = "{ \"RH\": 0.100, \"SMT 01\": 0.048, \"SMT 02\": 0.067, \"SMT 03\": 0.067 }",
                            ProductGroup = "AC"
                        },
                        new
                        {
                            Id = 55,
                            ModelCode = "LED-44600 (ACXE39C01500)",
                            Multiplier = 10.0,
                            ProcessTimesJson = "{ \"RH\": 0.100, \"SMT 01\": 0.065, \"SMT 02\": 0.067, \"SMT 03\": 0.067 }",
                            ProductGroup = "AC"
                        },
                        new
                        {
                            Id = 56,
                            ModelCode = "LED-49380",
                            Multiplier = 10.0,
                            ProcessTimesJson = "{ \"RH\": 0.100, \"SMT 01\": 0.065, \"SMT 02\": 0.067, \"SMT 03\": 0.067 }",
                            ProductGroup = "AC"
                        },
                        new
                        {
                            Id = 57,
                            ModelCode = "LED-49390",
                            Multiplier = 10.0,
                            ProcessTimesJson = "{ \"RH\": 0.100, \"SMT 01\": 0.065, \"SMT 02\": 0.067, \"SMT 03\": 0.067 }",
                            ProductGroup = "AC"
                        },
                        new
                        {
                            Id = 58,
                            ModelCode = "LED-51390",
                            Multiplier = 10.0,
                            ProcessTimesJson = "{ \"RH\": 0.100, \"SMT 01\": 0.065, \"SMT 02\": 0.067, \"SMT 03\": 0.067 }",
                            ProductGroup = "AC"
                        },
                        new
                        {
                            Id = 59,
                            ModelCode = "LED-51400",
                            Multiplier = 10.0,
                            ProcessTimesJson = "{ \"RH\": 0.100, \"SMT 01\": 0.065, \"SMT 02\": 0.067, \"SMT 03\": 0.067 }",
                            ProductGroup = "AC"
                        });
                });

            modelBuilder.Entity("backend.Models.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("backend.Models.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Machine")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachinePerformance")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductionReportId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductionReportId");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("backend.Models.Machine", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("MachineId");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("backend.Models.Model", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Components")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSaved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MachineTime")
                        .HasColumnType("REAL");

                    b.Property<string>("ModelCode")
                        .HasColumnType("TEXT");

                    b.Property<double>("Multiplier")
                        .HasColumnType("REAL");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<double>("PanelResult")
                        .HasColumnType("REAL");

                    b.Property<double>("PercentUsed")
                        .HasColumnType("REAL");

                    b.Property<double>("Plan")
                        .HasColumnType("REAL");

                    b.Property<double>("Result")
                        .HasColumnType("REAL");

                    b.Property<string>("SelectedPcbGroup")
                        .HasColumnType("TEXT");

                    b.Property<double>("TimeUsed")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("backend.Models.PerformanceLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LossTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsedTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("LogId");

                    b.HasIndex("MachineId");

                    b.ToTable("PerformanceLog");
                });

            modelBuilder.Entity("backend.Models.ProductionReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Performance")
                        .HasColumnType("TEXT");

                    b.Property<string>("SavedTimestamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<int>("Shift")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProductionReports");
                });

            modelBuilder.Entity("backend.Models.Issue", b =>
                {
                    b.HasOne("backend.Models.Model", null)
                        .WithMany("Issues")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Models.Line", b =>
                {
                    b.HasOne("backend.Models.ProductionReport", null)
                        .WithMany("Lines")
                        .HasForeignKey("ProductionReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Model", b =>
                {
                    b.HasOne("backend.Models.Line", null)
                        .WithMany("Models")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.PerformanceLog", b =>
                {
                    b.HasOne("backend.Models.Machine", "Machine")
                        .WithMany("PerformanceLogs")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("backend.Models.Line", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("backend.Models.Machine", b =>
                {
                    b.Navigation("PerformanceLogs");
                });

            modelBuilder.Entity("backend.Models.Model", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("backend.Models.ProductionReport", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
